/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package command-line-arguments */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
extern size_t _GoStringLen(_GoString_ s);
extern const char *_GoStringPtr(_GoString_ s);
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 3 "objects.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "rlwe.go"

#include <stdint.h>
#include <stdlib.h>
#include "../../../abi/c_types.h"

#ifndef GO_SDK_ERROR_STATUS_DEFINED
#define GO_SDK_ERROR_STATUS_DEFINED
typedef struct ErrorStatus {
    int code;
    char* message;
} ErrorStatus;
#endif

#line 1 "cgo-generated-wrapper"

#line 3 "bfv.go"

#include <stdint.h>
#include <stdlib.h>

#ifndef GO_SDK_ERROR_STATUS_DEFINED
#define GO_SDK_ERROR_STATUS_DEFINED
typedef struct ErrorStatus {
    int code;
    char* message;
} ErrorStatus;
#endif

#line 1 "cgo-generated-wrapper"

#line 3 "ckks.go"

#include <stdint.h>
#include <stdlib.h>

#ifndef GO_SDK_ERROR_STATUS_DEFINED
#define GO_SDK_ERROR_STATUS_DEFINED
typedef struct ErrorStatus {
    int code;
    char* message;
} ErrorStatus;
#endif

#line 1 "cgo-generated-wrapper"

#line 3 "bootstrap.go"

#include <stdint.h>
#include <stdlib.h>

#ifndef GO_SDK_ERROR_STATUS_DEFINED
#define GO_SDK_ERROR_STATUS_DEFINED
typedef struct ErrorStatus {
    int code;
    char* message;
} ErrorStatus;
#endif

#line 1 "cgo-generated-wrapper"

#line 3 "c_struct_import_export.go"

#include <stdint.h>
#include <stdlib.h>
#include "../../../abi/c_types.h"

#line 1 "cgo-generated-wrapper"

#line 3 "conversion.go"
 #include <stdint.h>

#line 1 "cgo-generated-wrapper"

#line 3 "multiparty.go"

#include <stdint.h>

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#if !defined(__cplusplus) || _MSVC_LANG <= 201402L
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
#include <complex>
typedef std::complex<float> GoComplex64;
typedef std::complex<double> GoComplex128;
#endif
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif

extern void ReleaseHandle(GoUint64 handleID);
extern void FreeGoString(char* s);
extern ErrorStatus NewPlaintext(GoUint64 parameterHandle, Metadata* metadata, uint64_t* plaintextHandle);
extern void GetPlaintextMetadata(GoUint64 plaintextHandle, Metadata* metadata);
extern ErrorStatus SerializePlaintext(GoUint64 plaintextHandle, GoUint8** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus DeserializePlaintext(GoUint8* rawData, uint64_t length, uint64_t* plaintextHandle);
extern ErrorStatus NewCiphertext(GoUint64 parameterHandle, GoInt degree, GoInt level, uint64_t* ciphertextHandle);
extern void GetCiphertextMetadata(GoUint64 ciphertextHandle, Metadata* metadata);
extern GoFloat64 SetCiphertextScale(GoUint64 ciphertextHandle, GoFloat64 scaleIn);
extern ErrorStatus SerializeCiphertext(GoUint64 ciphertextHandle, GoUint8** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus DeserializeCiphertext(GoUint8* rawData, uint64_t length, uint64_t* ciphertextHandle);
extern ErrorStatus CreateKeyGenerator(GoUint64 parameterHandle, uint64_t* keyGeneratorHandle);
extern ErrorStatus GenSecretKey(GoUint64 keyGeneratorHandle, uint64_t* secretKeyHandle);
extern ErrorStatus GenPublicKey(GoUint64 keyGeneratorHandle, GoUint64 secretKeyHandle, uint64_t* publicKeyHandle);
extern ErrorStatus SerializeSecretKey(GoUint64 secretKeyHandle, GoUint8** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus DeserializeSecretKey(GoUint8* rawData, uint64_t length, uint64_t* secretKeyHandle);
extern ErrorStatus SerializePublicKey(GoUint64 publicKeyHandle, GoUint8** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus DeserializePublicKey(GoUint8* rawData, uint64_t length, uint64_t* publicKeyHandle);
extern ErrorStatus CreateEncryptorFromSecretKey(GoUint64 parameterHandle, GoUint64 secretKeyHandle, uint64_t* encryptorHandle);
extern ErrorStatus CreateEncryptorFromPublicKey(GoUint64 parameterHandle, GoUint64 publicKeyHandle, uint64_t* encryptorHandle);
extern ErrorStatus CreateDecryptor(GoUint64 parameterHandle, GoUint64 secretKeyHandle, uint64_t* decryptorHandle);
extern ErrorStatus GenRelinearizationKey(GoUint64 keyGeneratorHandle, GoUint64 secretKeyHandle, GoInt level, uint64_t* relinearizationKeyHandle);
extern ErrorStatus GenGaloisKeysForRotations(GoUint64 keyGeneratorHandle, GoUint64 secretKeyHandle, int32_t* rotations, GoInt rotationCount, GoUint8 includeConjugation, GoInt level, uint64_t* galoisElements, uint64_t* galoisKeyHandles);
extern ErrorStatus CopyEvaluationKey(GoUint64 evaluationKeyHandle, uint64_t* targetHandle);
extern ErrorStatus SerializeEvaluationKey(GoUint64 evaluationKeyHandle, GoUint8** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus DeserializeEvaluationKey(GoUint8* rawData, uint64_t length, uint64_t* evaluationKeyHandle);
extern ErrorStatus CopyRelinearizationKey(GoUint64 relinearizationKeyHandle, uint64_t* targetHandle);
extern ErrorStatus GetRelinearizationKeyLevel(GoUint64 relinearizationKeyHandle, int* level);
extern ErrorStatus SerializeRelinearizationKey(GoUint64 relinearizationKeyHandle, GoUint8** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus DeserializeRelinearizationKey(GoUint8* rawData, uint64_t length, uint64_t* relinearizationKeyHandle);
extern ErrorStatus CopyGaloisKey(GoUint64 galoisKeyHandle, uint64_t* targetHandle);
extern ErrorStatus GetGaloisKeyElement(GoUint64 galoisKeyHandle, uint64_t* galoisElement);
extern ErrorStatus GetGaloisKeyLevel(GoUint64 galoisKeyHandle, int* level);
extern ErrorStatus SerializeGaloisKey(GoUint64 galoisKeyHandle, GoUint8** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus DeserializeGaloisKey(GoUint8* rawData, uint64_t length, uint64_t* galoisKeyHandle);
extern ErrorStatus SerializeEvaluationKeySet(GoUint64 evaluationKeySetHandle, GoUint8** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus DeserializeEvaluationKeySet(GoUint8* rawData, uint64_t length, uint64_t* evaluationKeySetHandle);
extern ErrorStatus GetEvaluationKeyRelinearizationKey(GoUint64 evaluationKeySetHandle, uint64_t* relinearizationKeyHandle);
extern ErrorStatus GetEvaluationKeyGaloisKeyCount(GoUint64 evaluationKeySetHandle, int* galoisKeyCount);
extern ErrorStatus GetEvaluationKeyGaloisKeyElements(GoUint64 evaluationKeySetHandle, uint64_t* galoisElements, GoInt galoisKeyCount);
extern ErrorStatus GetEvaluationKeyGaloisKey(GoUint64 evaluationKeySetHandle, GoUint64 galoisElement, uint64_t* galoisKeyHandle);
extern ErrorStatus SetEvaluationKeyRelinearizationKey(GoUint64 evaluationKeySetHandle, GoUint64 relinearizationKeyHandle);
extern ErrorStatus SetEvaluationKeyGaloisKey(GoUint64 evaluationKeySetHandle, GoUint64 galoisKeyHandle);
extern ErrorStatus SetEvaluationKeyGaloisKeys(GoUint64 evaluationKeySetHandle, uint64_t* galoisKeyHandles, GoInt galoisKeyCount);
extern ErrorStatus CreateEvaluationKeySet(GoUint64 relinearizationKeyHandle, uint64_t* galoisKeyHandles, GoInt galoisKeyCount, uint64_t* evaluationKeySetHandle);
extern ErrorStatus CreateBfvDefaultParameter(GoInt logN, GoUint64 T, uint64_t* parameterHandle);
extern ErrorStatus CreateBfvCustomParameter(GoInt logN, GoUint64 T, uint64_t* q, GoInt qLen, uint64_t* p, GoInt pLen, uint64_t* parameterHandle);
extern ErrorStatus CopyBfvParameter(GoUint64 parameterHandle, uint64_t* targetHandle);
extern ErrorStatus SerializeBfvParameter(GoUint64 parameterHandle, GoUint8** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus DeserializeBfvParameter(GoUint8* rawData, uint64_t length, uint64_t* parameterHandle);
extern ErrorStatus PrintBfvParameter(GoUint64 parameterHandle);
extern ErrorStatus GetBfvN(GoUint64 parameterHandle, int* n);
extern ErrorStatus GetBfvLogN(GoUint64 parameterHandle, int* logN);
extern ErrorStatus GetBfvMaxLevel(GoUint64 parameterHandle, int* maxLevel);
extern ErrorStatus GetBfvQ(GoUint64 parameterHandle, uint64_t* rawData);
extern ErrorStatus GetBfvP(GoUint64 parameterHandle, uint64_t* rawData, uint64_t* length);
extern ErrorStatus GetBfvT(GoUint64 parameterHandle, uint64_t* t);
extern ErrorStatus CreateBfvEncoder(GoUint64 parameterHandle, uint64_t* encoderHandle);
extern ErrorStatus CreateBfvEvaluator(GoUint64 parameterHandle, GoUint64 evaluationKeySetHandle, uint64_t* evaluatorHandle);
extern ErrorStatus SetBfvEvaluatorEvaluationKeySet(GoUint64 evaluatorHandle, GoUint64 evaluationKeySetHandle);
extern GoUint64 CopyBfvCiphertext(GoUint64 ciphertextHandle);
extern GoUint64 CopyBfvCiphertextTo(GoUint64 xCiphertextHandle, GoUint64 yCiphertextHandle);
extern ErrorStatus BfvEncode(GoUint64 encoderHandle, uint64_t* messageArray, GoInt messageLen, GoUint64 plaintextHandle);
extern ErrorStatus BfvDecode(GoUint64 encoderHandle, GoUint64 plaintextHandle, uint64_t** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus BfvEncrypt(GoUint64 encryptorHandle, GoUint64 plaintextHandle, uint64_t* ciphertextHandle);
extern ErrorStatus BfvDecrypt(GoUint64 decryptorHandle, GoUint64 ciphertextHandle, uint64_t* plaintextHandle);
extern ErrorStatus BfvAdd(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoUint64 op1OperandHandle, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvAddScalarInt(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoInt op1Value, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvAddScalar(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoInt64 op1Value, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvAddScalarUint(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoUint64 op1Value, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvSub(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoUint64 op1OperandHandle, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvSubScalarInt(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoInt op1Value, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvSubScalar(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoInt64 op1Value, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvSubScalarUint(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoUint64 op1Value, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvMult(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoUint64 op1OperandHandle, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvMultScalarInt(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoInt op1Value, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvMultScalar(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoInt64 op1Value, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvMultScalarUint(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoUint64 op1Value, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvRelinearize(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvDropLevel(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoInt32 levels, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvRescale(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, uint64_t* opOutCiphertextHandle);
extern ErrorStatus BfvRotateColumns(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, int32_t* steps, GoInt length, uint8_t useDefaultRotationKeys, uint64_t* opOutCiphertextHandles);
extern ErrorStatus BfvRotateRows(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, uint64_t* opOutCiphertextHandle);
extern ErrorStatus CreateCkksDefaultParameter(GoInt logN, uint64_t* parameterHandle);
extern ErrorStatus CreateCkksCustomParameter(GoInt logN, GoInt logDefaultScale, uint64_t* q, GoInt qLen, uint64_t* p, GoInt pLen, uint64_t* parameterHandle);
extern ErrorStatus CopyCkksParameter(GoUint64 parameterHandle, uint64_t* targetHandle);
extern ErrorStatus SerializeCkksParameter(GoUint64 parameterHandle, GoUint8** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus DeserializeCkksParameter(GoUint8* rawData, uint64_t length, uint64_t* parameterHandle);
extern ErrorStatus PrintCkksParameter(GoUint64 parameterHandle);
extern ErrorStatus GetCkksN(GoUint64 parameterHandle, int* n);
extern ErrorStatus GetCkksLogN(GoUint64 parameterHandle, int* logN);
extern ErrorStatus GetCkksMaxLevel(GoUint64 parameterHandle, int* maxLevel);
extern ErrorStatus GetCkksQ(GoUint64 parameterHandle, uint64_t* rawData);
extern ErrorStatus GetCkksP(GoUint64 parameterHandle, uint64_t* rawData, uint64_t* length);
extern ErrorStatus GetCkksLogMaxSlots(GoUint64 parameterHandle, int* logMaxSlots);
extern ErrorStatus GetCkksMaxSlots(GoUint64 parameterHandle, int* maxSlots);
extern ErrorStatus GetCkksDefaultScale(GoUint64 parameterHandle, double* defaultScale);
extern ErrorStatus GetCkksLogDefaultScale(GoUint64 parameterHandle, int* logDefaultScale);
extern ErrorStatus CreateCkksEncoder(GoUint64 parameterHandle, uint64_t* encoderHandle);
extern ErrorStatus CreateCkksEvaluator(GoUint64 parameterHandle, GoUint64 evaluationKeySetHandle, uint64_t* evaluatorHandle);
extern ErrorStatus SetCkksEvaluatorEvaluationKeySet(GoUint64 evaluatorHandle, GoUint64 evaluationKeySetHandle);
extern GoUint64 CopyCkksCiphertext(GoUint64 ciphertextHandle);
extern GoUint64 CopyCkksCiphertextTo(GoUint64 xCiphertextHandle, GoUint64 yCiphertextHandle);
extern ErrorStatus CkksEncodeReal(GoUint64 encoderHandle, double* messageArray, GoInt messageLen, GoUint64 plaintextHandle);
extern ErrorStatus CkksEncodeComplex(GoUint64 encoderHandle, double* messageArray, GoInt messageLen, GoUint64 plaintextHandle);
extern ErrorStatus CkksDecode(GoUint64 encoderHandle, GoUint64 plaintextHandle, double** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus CkksEncrypt(GoUint64 encryptorHandle, GoUint64 plaintextHandle, uint64_t* ciphertextHandle);
extern ErrorStatus CkksDecrypt(GoUint64 decryptorHandle, GoUint64 ciphertextHandle, uint64_t* plaintextHandle);
extern ErrorStatus CkksAdd(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoUint64 op1OperandHandle, uint64_t* opOutCiphertextHandle);
extern ErrorStatus CkksAddScalar(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoFloat64 op1Real, GoFloat64 op1Imag, uint64_t* opOutCiphertextHandle);
extern ErrorStatus CkksSub(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoUint64 op1OperandHandle, uint64_t* opOutCiphertextHandle);
extern ErrorStatus CkksSubScalar(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoFloat64 op1Real, GoFloat64 op1Imag, uint64_t* opOutCiphertextHandle);
extern ErrorStatus CkksMul(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoUint64 op1OperandHandle, uint64_t* opOutCiphertextHandle);
extern ErrorStatus CkksMulScalar(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoFloat64 op1Real, GoFloat64 op1Imag, uint64_t* opOutCiphertextHandle);
extern ErrorStatus CkksRelinearize(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, uint64_t* opOutCiphertextHandle);
extern ErrorStatus CkksDropLevel(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, GoInt32 levels, uint64_t* opOutCiphertextHandle);
extern ErrorStatus CkksRescale(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, uint64_t* opOutCiphertextHandle);
extern ErrorStatus CkksRotate(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, int32_t* steps, GoInt length, uint8_t useDefaultRotationKeys, uint64_t* opOutCiphertextHandles);
extern ErrorStatus CkksConjugate(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, uint64_t* opOutCiphertextHandle);
extern GoUint64 CkksPolyEvalStepFunction(GoUint64 evaluatorHandle, GoUint64 ciphertextHandle, GoFloat64 a, GoFloat64 b, GoInt degree, GoFloat64 threshold);
extern ErrorStatus GetCkksResidualParameterFromBtpParameter(GoUint64 parameterHandle, uint64_t* residualParameterHandle);
extern ErrorStatus CreateCkksBtpParameterFromResidualParameter(GoUint64 residualParameterHandle, uint64_t* parameterHandle);
extern ErrorStatus GenCkksBootstrappingEvaluationKeys(GoUint64 parameterHandle, GoUint64 secretKeyHandle, uint64_t* bootstrappingEvaluationKeysHandle, uint64_t* evkN1ToN2Handle, uint64_t* evkN2ToN1Handle, uint64_t* evkDenseToSparseHandle, uint64_t* evkSparseToDenseHandle, uint64_t* evaluationKeySetHandle);
extern ErrorStatus CreateCkksBootstrappingEvaluationKeys(GoUint64 evkN1ToN2Handle, GoUint64 evkN2ToN1Handle, GoUint64 evkDenseToSparseHandle, GoUint64 evkSparseToDenseHandle, GoUint64 evaluationKeySetHandle, uint64_t* bootstrappingEvaluationKeysHandle);
extern ErrorStatus GetCkksBootstrappingEvaluationKeys(GoUint64 bootstrappingEvaluationKeysHandle, uint64_t* evkN1ToN2Handle, uint64_t* evkN2ToN1Handle, uint64_t* evkDenseToSparseHandle, uint64_t* evkSparseToDenseHandle, uint64_t* evaluationKeySetHandle);
extern ErrorStatus SerializeCkksBootstrappingEvaluationKeys(GoUint64 bootstrappingEvaluationKeysHandle, GoUint8** rawData, uint64_t* length, uint64_t* dataHandle);
extern ErrorStatus DeserializeCkksBootstrappingEvaluationKeys(GoUint8* rawData, uint64_t length, uint64_t* bootstrappingEvaluationKeysHandle);
extern ErrorStatus SetCkksBootstrappingEvaluationKeySet(GoUint64 bootstrappingEvaluationKeysHandle, GoUint64 evaluationKeySetHandle);
extern ErrorStatus SetCkksBootstrappingEvaluationKeyN1ToN2(GoUint64 bootstrappingEvaluationKeysHandle, GoUint64 evaluationKeyHandle);
extern ErrorStatus SetCkksBootstrappingEvaluationKeyN2ToN1(GoUint64 bootstrappingEvaluationKeysHandle, GoUint64 evaluationKeyHandle);
extern ErrorStatus SetCkksBootstrappingEvaluationKeyDenseToSparse(GoUint64 bootstrappingEvaluationKeysHandle, GoUint64 evaluationKeyHandle);
extern ErrorStatus SetCkksBootstrappingEvaluationKeySparseToDense(GoUint64 bootstrappingEvaluationKeysHandle, GoUint64 evaluationKeyHandle);
extern ErrorStatus CreateCkksBtpEvaluator(GoUint64 parameterHandle, GoUint64 bootstrappingEvaluationKeysHandle, uint64_t* evaluatorHandle);
extern ErrorStatus CkksBootstrap(GoUint64 evaluatorHandle, GoUint64 op0CiphertextHandle, uint64_t* opOutCiphertextHandle);
extern ErrorStatus CkksBootstrapMany(GoUint64 evaluatorHandle, uint64_t* op0CiphertextHandles, GoInt op0Count, uint64_t* opOutCiphertextHandles);
extern ErrorStatus ImportCiphertext(GoUint64 parameterHandle, GoUint64 destHandle, Metadata* sourceMetadata, Metadata* targetMetadata, CCiphertext* cCiphertext);
extern void ExportPlaintext(GoUint64 parameterHandle, GoUint64 plaintextHandle, Metadata* metadata, CPlaintext* plaintext);
extern void ExportCiphertext(GoUint64 parameterHandle, GoUint64 ciphertextHandle, Metadata* metadata, CCiphertext* ciphertext);
extern void ExportEvaluationKey(GoUint64 parameterHandle, GoUint64 evaluationKeyHandle, GoInt levelP, Metadata* metadata, CEvaluationKey* evaluationKey);
extern void BfvPolyNttInplace(GoUint64 parameter_handle, uint64_t* data, GoInt level_q, GoInt level_p);
extern void BfvPolyInvNttInplace(GoUint64 parameter_handle, uint64_t* data, GoInt level_q, GoInt level_p);
extern void BfvPolyMulByPow2Inplace(GoUint64 parameter_handle, uint64_t* data, GoInt level_q, GoInt level_p, GoInt pow2);
extern void CkksPolyNttInplace(GoUint64 parameter_handle, uint64_t* data, GoInt level_q, GoInt level_p);
extern void CkksPolyInvNttInplace(GoUint64 parameter_handle, uint64_t* data, GoInt level_q, GoInt level_p);
extern void CkksPolyMulByPow2Inplace(GoUint64 parameter_handle, uint64_t* data, GoInt level_q, GoInt level_p, GoInt pow2);
extern GoUint64 CreateRandomDBfvContext(GoUint64 context_handle, GoUint8* crs_seed, GoFloat64 sigma_smudging);
extern GoUint64 GetDBfvBfvContext(GoUint64 context_handle);
extern GoUint64 CreateCKGContext(GoUint64 context_handle);
extern GoUint64 GenDBfvPublicKeyShare(GoUint64 context_handle);
extern GoUint64 AggregateDBfvPublicKeyShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern void SetDBfvPublicKey(GoUint64 context_handle, GoUint64 share_handle);
extern GoUint64 SerializeDBfvPublicKeyShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvPublicKeyShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 CreateE2SContext(GoUint64 context_handle);
extern GoUint64 GenDBfvE2SPublicAndSecretShare(GoUint64 context_handle, GoUint64 ciphertext_handle, uint64_t* secret_share_handle);
extern GoUint64 AggregateDBfvE2SCKSShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern GoUint64 GetDBfvE2SSecretShare(GoUint64 context_handle, GoUint64 ciphertext_handle, GoUint64 public_share_handle, GoUint64 secret_share_handle);
extern GoUint64 AggregateDBfvAdditiveShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern GoUint64 SetDBfvE2SPlaintextRingT(GoUint64 context_handle, GoUint64 secret_share_handle);
extern GoUint64 SerializeDBfvCKSShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvE2SCKSShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 SerializeDBfvAdditiveShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvAdditiveShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 CreateS2EContext(GoUint64 context_handle);
extern GoUint64 GenDBfvS2EPublicShare(GoUint64 context_handle, GoUint64 secret_share_handle);
extern GoUint64 AggregateDBfvS2ECKSShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern GoUint64 SetDBfvS2ECiphertext(GoUint64 context_handle, GoUint64 public_share_handle);
extern GoUint64 DeserializeDBfvS2ECKSShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 CreateRKGContext(GoUint64 context_handle);
extern GoUint64 GenDBfvRelinKeyShareRoundOne(GoUint64 context_handle, uint64_t* eph_sk_handle);
extern GoUint64 AggregateDBfvRelinKeyShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern GoUint64 GenDBfvRelinKeyShareRoundTwo(GoUint64 context_handle, GoUint64 eph_sk_handle, GoUint64 share1_handle);
extern void SetDBfvRelinKey(GoUint64 context_handle, GoUint64 share1_handle, GoUint64 share2_handle);
extern GoUint64 SerializeDBfvRelinKeyShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvRelinKeyShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 CreateRTGContext(GoUint64 context_handle);
extern GoInt GenDBfvGaloisKeyShare(GoUint64 context_handle, GoInt32* rots, GoInt rots_length, GoUint8 include_swap_rows, uint64_t* share_handles);
extern GoInt AggregateDBfvGaloisKeyShare(GoUint64 context_handle, uint64_t* x0_share_handles, uint64_t* x1_share_handles, GoInt length, uint64_t* y_share_handles);
extern void SetDBfvRotationKey(GoUint64 context_handle, GoInt32* rots, GoInt rots_length, GoUint8 include_swap_rows, uint64_t* share_handles);
extern GoUint64 SerializeDBfvGaloisKeyShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvGaloisKeyShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 CreateRefreshContext(GoUint64 context_handle);
extern GoUint64 GenDBfvRefreshShare(GoUint64 context_handle, GoUint64 ciphertext_handle);
extern GoUint64 AggregateDBfvRefreshShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern GoUint64 DBfvRefreshFinalize(GoUint64 context_handle, GoUint64 ciphertext_handle, GoUint64 share_handle);
extern GoUint64 SerializeDBfvRefreshShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvRefreshShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);
extern GoUint64 CreateRefreshAndPermuteContext(GoUint64 context_handle);
extern GoUint64 GenDBfvRefreshAndPermuteShare(GoUint64 context_handle, GoUint64 ciphertext_handle, uint64_t* permute);
extern GoUint64 AggregateDBfvRefreshAndPermuteShare(GoUint64 context_handle, GoUint64 x0_share_handle, GoUint64 x1_share_handle);
extern GoUint64 DBfvRefreshAndPermuteTransform(GoUint64 context_handle, GoUint64 ciphertext_handle, uint64_t* permute, GoUint64 share_handle);
extern GoUint64 SerializeDBfvRefreshAndPermuteShare(GoUint64 share_handle, GoUint8** raw_data, uint64_t* length);
extern GoUint64 DeserializeDBfvvRefreshAndPermuteShare(GoUint64 context_handle, GoUint8* raw_data, uint64_t length);

#ifdef __cplusplus
}
#endif
